### ISSUE TITLE
requirements question

### ISSUE THREAD

**Issue by Tristam1211** [slptongji/TriKF#1]
Dear Author
  I would like to reproduce your side of the paper, could you please provide the detailed requirements file as well as the readme file. Also, do you have any suggestions for me?
  I look forward to your reply and hope to have a chance to learn more from your work.

**Comment by Tim4Dec** [comment]
Thanks for the suggestion. We have uploaded the requirements.txt to provide detailed dependencies for the python environment.

**Comment by Tim4Dec** [comment]
> Dear Author I would like to reproduce your side of the paper, could you please provide the detailed requirements file as well as the readme file. Also, do you have any suggestions for me? I look forward to your reply and hope to have a chance to learn more from your work.


Thanks for the suggestion. We have uploaded the requirements.txt to provide detailed dependencies for the python environment.
